### ISSUE TITLE
Improvement in the UI of Schedule Fragment

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-droidgen#1738]
**Actual Behaviour**

There are certain points on improvijg the UI of schedule fragment.

1. removing the session description. that is only showing the title along with time and location.

2. show length ( end time - start time ) instead of the start time and end time.

3. show the time 24 hour based and remove the AM and PM.

4. add a video button along with the track imageview.

5. remove sorting option and replace it with the filter used as a floating action button as of now.

**Expected Behaviour**

Making UI changes to the fragment.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

-

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/31 

@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
please check which points seem apt to you.

**Comment by shreyasnbhat** [comment]
@arp95 You could make the title bold of the session bold.
And point 2 would only make sense if the sessions are sorted by time only.
And why remove the sorting option?

**Comment by arp95** [comment]
@shreyasnbhat 
leave the sorting option. right now we can have it.
point 2 means that we already have the starting time at the top right. so we can show the length of session from session_type.json as the start time is already at the top. did you get it?

**Comment by shreyasnbhat** [comment]
@arp95  You are saying that we would have starting time and session length instead of start and end times right?

**Comment by arp95** [comment]
yep

**Comment by arp95** [comment]
@iamareebjamal 
please add this to a milestone and provide which points are useful according to you.

**Comment by iamareebjamal** [comment]
- Track image is not supported so that won't work. 
- Length can be shown with end time because someone would want to see the end time without the mental calculation. Furthermore, several sessions have same starting time with different end times making it confusing for users.
- I agree that description can be removed
- 24 hour time should be preferred, but don't remove the DateUtils method if we'd want to add preference option in settings
- About video button, I guess we should not add more things to it. Make it like web app, very concise and only showing required information
- Sorting should be present

**Comment by arp95** [comment]
so i am doing the following then as per review:

1: removing the description
2: making title bold
3: showing 24 hour time

**Comment by shreyasnbhat** [comment]
@iamareebjamal Do you think that the sticky headers of the list use the `colorAccent` instead of the default grey? Like in the search and the home?
@arp95 Suggestions?

**Comment by arp95** [comment]
i dont think so.
