### ISSUE TITLE
Create ViewModel for SpeakerDetailsActivity

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-droidgen#2056]
**Actual Behaviour**

There is no ViewModel for the SpeakerDetailsActivity

**Expected Behaviour**

There should be one.

**Would you like to work on the issue?**

Yes

**Comment by dr0pdb** [comment]
@nikit19 Can i take this in case you haven't started working on it ? I accidently created the ViewModel for it instead of ```SessionDetailsActivity```. You can create the ViewModel for ```SessionDetailsActivity``` i.e. #2052  instead of this activity.
I am submitting a PR for this issue. In case you've started working on it, then drop a comment on my PR and i will close it.

**Comment by nikit19** [comment]
@srv-twry actually I had already made the ViewModel for this activity but I wanted to send the PR after I finished correcting my previous PRs for viewmodels. I really wouldn't have mind you sending the PR #2074  if I hadn't worked on it. So if you could please close the PR, I can send mine. Thanks
