### ISSUE TITLE
Redundant method in LocationsFragment

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2136]
**Actual Behaviour**

The method `onLocationsDownloadDone` is redundant as it is not used anywhere.

**Expected Behaviour**

The method should not be present.

**Would you like to work on the issue?**

Yes

**Comment by dr0pdb** [comment]
@dreadpool2 As far i know it is being used by ```otto``` when you use the swipe to refresh. The ```@Subscribe``` annotation does the trick here. 
One more thing that i would recommend doing is tagging the maintainers and asking whether the issue is actually correct and ways to implement it, before starting to work on it. It helps :smile:

**Comment by dreadpool2** [comment]
@srv-twry Oh yes !I again completely ignored the Subscribe annotation  😓
