### ISSUE TITLE
Adding Email notification of latest event

### ISSUE THREAD

**Issue by shivaraju07** [fossasia/open-event-droidgen#2290]
**Actual Behaviour**

API supports Email notifications but it is not implemented in the application.

**Expected Behaviour**

As API supports the Email notification, It would be nice to send
 every day's live feed on his/her email or 
Any event that is bookmarked and the event is about to start in 1 day or
upcoming sessions etc.
or any push notification?

**Would you like to work on the issue?**

Yes

@srv-twry , @iamareebjamal  views?

**Comment by simarsingh24** [comment]
IMO It would be better to leave email-based notifications for purchase-related work (not implemented right now) because there is no point of sending the live feed to email. And for bookmarked events, App based notifications and the reminder would be good enough? what do you think @srv-twry  @iamareebjamal

**Comment by iamareebjamal** [comment]
This is server related functionality, not the responsibility of the app

**Comment by iamareebjamal** [comment]
Notification for the bookmarked events are already present
