### ISSUE TITLE
Filter function in schedule module is not working 

### ISSUE THREAD

**Issue by sejalgoyal** [fossasia/open-event-droidgen#2321]
**Actual Behaviour**

After applying filter nothing is changed in the list of event
 
**Expected Behaviour**

After applying filter only related events should be displayed

**Screenshots of the issue**

![screenshot_2018-02-07-01-09-09-710_org fossasia openevent](https://user-images.githubusercontent.com/14599142/35880663-8a88f7e2-0ba4-11e8-8520-3419fb8d09b5.png)
![screenshot_2018-02-07-01-09-28-507_org fossasia openevent](https://user-images.githubusercontent.com/14599142/35880677-957cf162-0ba4-11e8-8604-b085b81b3e1d.png)

**Would you like to work on the issue?**

Yes,I want to.

**Comment by dr0pdb** [comment]
@sejalgoyal Hi!, Yes i have also seen this issue, but i overlooked it since we are already going to move the filter functionality to the ViewModel from the View in #2066 . 
Infact that issue hasn't been taken by anyone. Why don't you close this and take that one ? :smile: 
After moving it to ViewModel also fix this problem in that issue itself :+1: 
Drop a comment on that issue in case you want to work on that.

**Comment by sejalgoyal** [comment]
Okay!! i'm closing this and will work on that issue.
